version: "3.8"
services:
  mysqldb:
    image: mysql:8.3
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpfoyer_db
    ports:
      - 3306:3306
    networks:
      - my-network
    volumes:
      - db:/var/lib/mysql
  app-timesheet:
    depends_on:
      - mysqldb
    image: d3fcec7948f4/tp-foyer:${BUILD_NUMBER}
    #build : ./
    restart: on-failure
    ports:
      - 8089:8089
    networks:
          - my-network
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpfoyer_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
volumes:
  db :
networks:
  my-network:
    driver: bridge